development:
  adapter: postgresql
  encoding: unicode
  database: recipes_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: recipes_test
  pool: 5
  username: postgres
  password: