# development:
#   adapter: postgresql
#   encoding: unicode
#   database: app_development
#   pool: 5
#   username: postgres
#   password:

# test:
#   adapter: postgresql
#   encoding: unicode
#   database: app_test
#   pool: 5
#   username: postgres
#   password:

default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: <%= ENV['PG_PASSWORD'] %> # to change password go to docker-compose.yml
  pool: 5

development:
  <<: *default
  database: app_development


test:
  <<: *default
  database: app_test
